# Generated by Django 5.0.7 on 2024-07-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
