# Generated by Django 5.0.7 on 2024-07-22 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_order_location_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='users.order'),
        ),
    ]
