# Generated by Django 5.0.7 on 2024-07-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_proposal_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tg_username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
