# Generated by Django 5.0.7 on 2024-07-27 10:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_job_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Admin', 'Админ'), ('Customer', 'Заказчик'), ('Worker', 'Работник')], max_length=20), blank=True, default=list, size=None),
        ),
    ]
