# Generated by Django 5.0.7 on 2024-07-28 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_role_customuser_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_appeal',
        ),
        migrations.RemoveField(
            model_name='job',
            name='payment_appeal',
        ),
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_card', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal', models.TextField(blank=True, null=True)),
                ('to', models.CharField(blank=True, choices=[('Payment', 'Оплата'), ('Job', 'Работа')], max_length=20, null=True)),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='users.job')),
            ],
        ),
    ]
