# Generated by Django 5.0.7 on 2024-07-29 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_job_job_appeal_remove_job_payment_appeal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='appeal',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='job',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='job',
            name='review',
        ),
        migrations.AddField(
            model_name='appeal',
            name='problem',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='job_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='users.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appeal',
            name='to',
            field=models.CharField(choices=[('Payment', 'Оплата'), ('Job', 'Работа')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('payment', 'Payment'), ('warning', 'Warning'), ('review', 'Review'), ('completed', 'Completed')], default='in_progress', max_length=15),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('comment', models.TextField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cv')),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='users.cv')),
            ],
        ),
    ]
