# Generated by Django 5.0.7 on 2024-07-29 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_review_order_review_job_alter_review_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='users.job'),
        ),
    ]
