# Generated by Django 5.0.7 on 2024-07-29 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_bankcard_owner_alter_cv_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appeal',
            old_name='job_id',
            new_name='job',
        ),
        migrations.AddField(
            model_name='appeal',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appeal',
            name='whom',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='users.cv'),
            preserve_default=False,
        ),
    ]
