# Generated by Django 5.0.7 on 2024-08-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_image_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
    ]
