# Generated by Django 5.0.7 on 2024-08-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_order_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cv_images/'),
        ),
    ]
