# Generated by Django 5.0.7 on 2024-08-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_cv_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='payment_confirmed_by_customer',
            field=models.CharField(choices=[('Approved', 'approved'), ('Problem', 'problem'), ('Default', 'default')], default='Default', max_length=15),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_confirmed_by_worker',
            field=models.CharField(choices=[('Approved', 'approved'), ('Problem', 'problem'), ('Default', 'default')], default='Default', max_length=15),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_successful',
            field=models.BooleanField(default=False),
        ),
    ]
