# Generated by Django 5.0.7 on 2024-08-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_customuser_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='payment_successful',
        ),
        migrations.AddField(
            model_name='job',
            name='review_written_by_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='review_written_by_worker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('job', 'Job')], default='open', max_length=10),
        ),
    ]
