# Generated by Django 5.0.7 on 2024-08-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_job_payment_successful_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('waiting', 'Waiting'), ('canceled', 'Canceled')], default='waiting', max_length=10),
        ),
    ]
