version: '3.9'

services:
  redis:
    container_name: LabbayHizmatda_redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  db:
    container_name: LabbayHizmatda_db
    image: postgres:16
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rest-auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  web:
    build: .
    container_name: LabbayHizmatda_web
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DB_NAME: rest-auth
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      CACHE_URL: redis://redis:6379/1 
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  pgdata:
